### PR TITLE
Get all games between SL players & all players

### PR DESCRIPTION
**Pull request by janakerman**
Previously we were only getting the first page... now we get them all! There's a lot more detail in the individual commit messages.

### CODE REVIEW

**Review by ZinatWali — COMMENTED** [review]
Like the usage of generics. Why are the parse methods static?

**Comment by janakerman** [comment]
I made them static because they don't rely on any instance state - they should probably be pulled out into a parser class (or the model class itself?).

**Review by ZinatWali — APPROVED** [review]
We might have to refactor the classes a bit more if we want to start unit testing them. But other than that, it is looking great.

**Comment by janakerman** [comment]
I'll be changing the class structure up a little bit in my next thread of work

**Pull request merged**
